// @generated by protoc-gen-es v2.0.0
// @generated from file anduril/tasks/v2/catalog.pub.proto (package anduril.tasks.v2, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";

/**
 * Describes the file anduril/tasks/v2/catalog.pub.proto.
 */
export const file_anduril_tasks_v2_catalog_pub = /*@__PURE__*/
  fileDesc("CiJhbmR1cmlsL3Rhc2tzL3YyL2NhdGFsb2cucHViLnByb3RvEhBhbmR1cmlsLnRhc2tzLnYyImUKC1Rhc2tDYXRhbG9nEjoKEHRhc2tfZGVmaW5pdGlvbnMYASADKAsyIC5hbmR1cmlsLnRhc2tzLnYyLlRhc2tEZWZpbml0aW9uEhoKEmlzX2Fzc2V0X2luaGliaXRlZBgCIAEoCCJGCg5UYXNrRGVmaW5pdGlvbhIeChZ0YXNrX3NwZWNpZmljYXRpb25fdXJsGAEgASgJEhQKDGRpc3BsYXlfbmFtZRgCIAEoCULIAQoUY29tLmFuZHVyaWwudGFza3MudjJCD0NhdGFsb2dQdWJQcm90b1ABWj1naGUuYW5kdXJpbC5kZXYvYW5kdXJpbC9hbmR1cmlsYXBpcy1nby9hbmR1cmlsL3Rhc2tzL3YyO3Rhc2tzogIDQVRYqgIQQW5kdXJpbC5UYXNrcy5WMsoCEEFuZHVyaWxcVGFza3NcVjLiAhxBbmR1cmlsXFRhc2tzXFYyXEdQQk1ldGFkYXRh6gISQW5kdXJpbDo6VGFza3M6OlYyYgZwcm90bzM");

/**
 * Describes the message anduril.tasks.v2.TaskCatalog.
 * Use `create(TaskCatalogSchema)` to create a new message.
 */
export const TaskCatalogSchema = /*@__PURE__*/
  messageDesc(file_anduril_tasks_v2_catalog_pub, 0);

/**
 * Describes the message anduril.tasks.v2.TaskDefinition.
 * Use `create(TaskDefinitionSchema)` to create a new message.
 */
export const TaskDefinitionSchema = /*@__PURE__*/
  messageDesc(file_anduril_tasks_v2_catalog_pub, 1);

