// @generated by protoc-gen-es v2.0.0
// @generated from file anduril/auth/v2/idp.pub.proto (package anduril.auth.v2, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";

/**
 * Describes the file anduril/auth/v2/idp.pub.proto.
 */
export const file_anduril_auth_v2_idp_pub = /*@__PURE__*/
  fileDesc("Ch1hbmR1cmlsL2F1dGgvdjIvaWRwLnB1Yi5wcm90bxIPYW5kdXJpbC5hdXRoLnYyIk0KEEdldFNTT1VSTFJlcXVlc3QSDQoFZW1haWwYASABKAkSFAoMcmVkaXJlY3RfdXJsGAIgASgJEhQKDGFwcGVuZF90b2tlbhgDIAEoCCKEAgoRR2V0U1NPVVJMUmVzcG9uc2USSAoNaW52YWxpZF9lbWFpbBgBIAEoCzIvLmFuZHVyaWwuYXV0aC52Mi5HZXRTU09VUkxSZXNwb25zZS5JbnZhbGlkRW1haWxIABJGCgx2YWxpZF9kb21haW4YAiABKAsyLi5hbmR1cmlsLmF1dGgudjIuR2V0U1NPVVJMUmVzcG9uc2UuVmFsaWREb21haW5IABoeCgxJbnZhbGlkRW1haWwSDgoGcmVhc29uGAEgASgJGjEKC1ZhbGlkRG9tYWluEiIKBGlkcHMYASADKAsyFC5hbmR1cmlsLmF1dGgudjIuSWRwQgoKCHJlc3BvbnNlIpUBCgNJZHASMAoIaW50ZXJuYWwYASABKAsyHC5hbmR1cmlsLmF1dGgudjIuSW50ZXJuYWxJRFBIABIwCghleHRlcm5hbBgCIAEoCzIcLmFuZHVyaWwuYXV0aC52Mi5FeHRlcm5hbElEUEgAEiMKA3BpdhgDIAEoCzIULmFuZHVyaWwuYXV0aC52Mi5QSVZIAEIFCgNpZHAiDQoLSW50ZXJuYWxJRFAiPwoLRXh0ZXJuYWxJRFASDAoEbmFtZRgBIAEoCRIPCgdzc29fdXJsGAIgASgJEhEKCXVuaXF1ZV9pZBgDIAEoCSIFCgNQSVYyWgoESWRwcxJSCglHZXRTU09VUkwSIS5hbmR1cmlsLmF1dGgudjIuR2V0U1NPVVJMUmVxdWVzdBoiLmFuZHVyaWwuYXV0aC52Mi5HZXRTU09VUkxSZXNwb25zZUK9AQoTY29tLmFuZHVyaWwuYXV0aC52MkILSWRwUHViUHJvdG9QAVo7Z2hlLmFuZHVyaWwuZGV2L2FuZHVyaWwvYW5kdXJpbGFwaXMtZ28vYW5kdXJpbC9hdXRoL3YyO2F1dGiiAgNBQViqAg9BbmR1cmlsLkF1dGguVjLKAg9BbmR1cmlsXEF1dGhcVjLiAhtBbmR1cmlsXEF1dGhcVjJcR1BCTWV0YWRhdGHqAhFBbmR1cmlsOjpBdXRoOjpWMmIGcHJvdG8z");

/**
 * Describes the message anduril.auth.v2.GetSSOURLRequest.
 * Use `create(GetSSOURLRequestSchema)` to create a new message.
 */
export const GetSSOURLRequestSchema = /*@__PURE__*/
  messageDesc(file_anduril_auth_v2_idp_pub, 0);

/**
 * Describes the message anduril.auth.v2.GetSSOURLResponse.
 * Use `create(GetSSOURLResponseSchema)` to create a new message.
 */
export const GetSSOURLResponseSchema = /*@__PURE__*/
  messageDesc(file_anduril_auth_v2_idp_pub, 1);

/**
 * Describes the message anduril.auth.v2.GetSSOURLResponse.InvalidEmail.
 * Use `create(GetSSOURLResponse_InvalidEmailSchema)` to create a new message.
 */
export const GetSSOURLResponse_InvalidEmailSchema = /*@__PURE__*/
  messageDesc(file_anduril_auth_v2_idp_pub, 1, 0);

/**
 * Describes the message anduril.auth.v2.GetSSOURLResponse.ValidDomain.
 * Use `create(GetSSOURLResponse_ValidDomainSchema)` to create a new message.
 */
export const GetSSOURLResponse_ValidDomainSchema = /*@__PURE__*/
  messageDesc(file_anduril_auth_v2_idp_pub, 1, 1);

/**
 * Describes the message anduril.auth.v2.Idp.
 * Use `create(IdpSchema)` to create a new message.
 */
export const IdpSchema = /*@__PURE__*/
  messageDesc(file_anduril_auth_v2_idp_pub, 2);

/**
 * Describes the message anduril.auth.v2.InternalIDP.
 * Use `create(InternalIDPSchema)` to create a new message.
 */
export const InternalIDPSchema = /*@__PURE__*/
  messageDesc(file_anduril_auth_v2_idp_pub, 3);

/**
 * Describes the message anduril.auth.v2.ExternalIDP.
 * Use `create(ExternalIDPSchema)` to create a new message.
 */
export const ExternalIDPSchema = /*@__PURE__*/
  messageDesc(file_anduril_auth_v2_idp_pub, 4);

/**
 * Describes the message anduril.auth.v2.PIV.
 * Use `create(PIVSchema)` to create a new message.
 */
export const PIVSchema = /*@__PURE__*/
  messageDesc(file_anduril_auth_v2_idp_pub, 5);

/**
 * @generated from service anduril.auth.v2.Idps
 */
export const Idps = /*@__PURE__*/
  serviceDesc(file_anduril_auth_v2_idp_pub, 0);

