// @generated by protoc-gen-es v1.7.2 with parameter "js_import_style=legacy_commonjs"
// @generated from file anduril/auth/v2/tokens.pub.proto (package anduril.auth.v2, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, Duration, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message anduril.auth.v2.RefreshOidcTokensRequest
 */
export declare class RefreshOidcTokensRequest extends Message<RefreshOidcTokensRequest> {
  /**
   * @generated from field: string refresh_token = 1;
   */
  refreshToken: string;

  constructor(data?: PartialMessage<RefreshOidcTokensRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "anduril.auth.v2.RefreshOidcTokensRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RefreshOidcTokensRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RefreshOidcTokensRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RefreshOidcTokensRequest;

  static equals(a: RefreshOidcTokensRequest | PlainMessage<RefreshOidcTokensRequest> | undefined, b: RefreshOidcTokensRequest | PlainMessage<RefreshOidcTokensRequest> | undefined): boolean;
}

/**
 * @generated from message anduril.auth.v2.RefreshOidcTokensResponse
 */
export declare class RefreshOidcTokensResponse extends Message<RefreshOidcTokensResponse> {
  /**
   * The length of time that the token is valid for. User agents must refresh the user's token within this time
   * period.
   *
   * @generated from field: google.protobuf.Duration token_validity_duration = 1;
   */
  tokenValidityDuration?: Duration;

  /**
   * @generated from field: string refresh_token = 2;
   */
  refreshToken: string;

  /**
   * @generated from field: string id_token = 3;
   */
  idToken: string;

  constructor(data?: PartialMessage<RefreshOidcTokensResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "anduril.auth.v2.RefreshOidcTokensResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RefreshOidcTokensResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RefreshOidcTokensResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RefreshOidcTokensResponse;

  static equals(a: RefreshOidcTokensResponse | PlainMessage<RefreshOidcTokensResponse> | undefined, b: RefreshOidcTokensResponse | PlainMessage<RefreshOidcTokensResponse> | undefined): boolean;
}

