// @generated by protoc-gen-es v1.7.2 with parameter "js_import_style=legacy_commonjs"
// @generated from file anduril/entitymanager/v1/geoentity.pub.proto (package anduril.entitymanager.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import type { Position } from "./location.pub_pb.js";
import type { Color } from "../../type/color.pub_pb.js";

/**
 * The type of geo entity.
 *
 * @generated from enum anduril.entitymanager.v1.GeoType
 */
export declare enum GeoType {
  /**
   * @generated from enum value: GEO_TYPE_INVALID = 0;
   */
  INVALID = 0,

  /**
   * @generated from enum value: GEO_TYPE_GENERAL = 1;
   */
  GENERAL = 1,

  /**
   * @generated from enum value: GEO_TYPE_HAZARD = 2;
   */
  HAZARD = 2,

  /**
   * @generated from enum value: GEO_TYPE_EMERGENCY = 3;
   */
  EMERGENCY = 3,

  /**
   * Fire support coordination measure
   *
   * @generated from enum value: GEO_TYPE_FSCM = 4;
   */
  FSCM = 4,

  /**
   * Engagement zones allow for engaging an entity if it comes within the zone of another entity.
   *
   * @generated from enum value: GEO_TYPE_ENGAGEMENT_ZONE = 5;
   */
  ENGAGEMENT_ZONE = 5,

  /**
   * @generated from enum value: GEO_TYPE_CONTROL_AREA = 6;
   */
  CONTROL_AREA = 6,

  /**
   * @generated from enum value: GEO_TYPE_BULLSEYE = 7;
   */
  BULLSEYE = 7,

  /**
   * Airspace Coordinating Measure
   *
   * @generated from enum value: GEO_TYPE_ACM = 8;
   */
  ACM = 8,

  /**
   * Maneuver Control Measure
   *
   * @generated from enum value: GEO_TYPE_MCM = 9;
   */
  MCM = 9,
}

/**
 * Type of an emergency.
 *
 * @generated from enum anduril.entitymanager.v1.EmergencyType
 */
export declare enum EmergencyType {
  /**
   * @generated from enum value: EMERGENCY_TYPE_INVALID = 0;
   */
  INVALID = 0,

  /**
   * @generated from enum value: EMERGENCY_TYPE_DOWN_AIRCRAFT = 1;
   */
  DOWN_AIRCRAFT = 1,

  /**
   * @generated from enum value: EMERGENCY_TYPE_MAN_IN_WATER = 2;
   */
  MAN_IN_WATER = 2,

  /**
   * @generated from enum value: EMERGENCY_TYPE_DITCHING = 3;
   */
  DITCHING = 3,

  /**
   * @generated from enum value: EMERGENCY_TYPE_BAILOUT = 4;
   */
  BAILOUT = 4,

  /**
   * @generated from enum value: EMERGENCY_TYPE_DISTRESSED_VEHICLE = 5;
   */
  DISTRESSED_VEHICLE = 5,

  /**
   * @generated from enum value: EMERGENCY_TYPE_GROUND_INCIDENT = 6;
   */
  GROUND_INCIDENT = 6,

  /**
   * @generated from enum value: EMERGENCY_TYPE_MEDICAL = 7;
   */
  MEDICAL = 7,

  /**
   * @generated from enum value: EMERGENCY_TYPE_ISOLATED_PERSON = 8;
   */
  ISOLATED_PERSON = 8,
}

/**
 * @generated from enum anduril.entitymanager.v1.ControlAreaType
 */
export declare enum ControlAreaType {
  /**
   * @generated from enum value: CONTROL_AREA_TYPE_INVALID = 0;
   */
  INVALID = 0,

  /**
   * @generated from enum value: CONTROL_AREA_TYPE_KEEP_IN_ZONE = 1;
   */
  KEEP_IN_ZONE = 1,

  /**
   * @generated from enum value: CONTROL_AREA_TYPE_KEEP_OUT_ZONE = 2;
   */
  KEEP_OUT_ZONE = 2,

  /**
   * Zone for an autonomous asset to nose-dive into
   * when its assignment has been concluded
   *
   * @generated from enum value: CONTROL_AREA_TYPE_DITCH_ZONE = 3;
   */
  DITCH_ZONE = 3,

  /**
   * Areas where we do not process radar detections
   *
   * @generated from enum value: CONTROL_AREA_TYPE_OBSERVATION_EXCLUSION = 4;
   */
  OBSERVATION_EXCLUSION = 4,

  /**
   * Areas where we process radar detections exclusively
   *
   * @generated from enum value: CONTROL_AREA_TYPE_OBSERVATION_INCLUSION = 5;
   */
  OBSERVATION_INCLUSION = 5,

  /**
   * Areas where we elevate interrogation priority
   *
   * @generated from enum value: CONTROL_AREA_TYPE_OBSERVATION_PRIORITY = 6;
   */
  OBSERVATION_PRIORITY = 6,
}

/**
 * @generated from enum anduril.entitymanager.v1.FSCMDetailType
 */
export declare enum FSCMDetailType {
  /**
   * @generated from enum value: FSCM_DETAIL_TYPE_INVALID = 0;
   */
  FSCM_DETAIL_TYPE_INVALID = 0,

  /**
   * @generated from enum value: FSCM_DETAIL_TYPE_DEAD_SPACE_AREA = 1;
   */
  FSCM_DETAIL_TYPE_DEAD_SPACE_AREA = 1,

  /**
   * @generated from enum value: FSCM_DETAIL_TYPE_NO_FIRE_AREA = 2;
   */
  FSCM_DETAIL_TYPE_NO_FIRE_AREA = 2,

  /**
   * @generated from enum value: FSCM_DETAIL_TYPE_FREE_FIRE_AREA = 3;
   */
  FSCM_DETAIL_TYPE_FREE_FIRE_AREA = 3,

  /**
   * @generated from enum value: FSCM_DETAIL_TYPE_RESTRICTIVE_FIRE_AREA = 4;
   */
  FSCM_DETAIL_TYPE_RESTRICTIVE_FIRE_AREA = 4,

  /**
   * @generated from enum value: FSCM_DETAIL_TYPE_SAFE_FIRE_AREA = 5;
   */
  FSCM_DETAIL_TYPE_SAFE_FIRE_AREA = 5,

  /**
   * @generated from enum value: FSCM_DETAIL_TYPE_AIRSPACE_COORDINATION_AREA = 6;
   */
  FSCM_DETAIL_TYPE_AIRSPACE_COORDINATION_AREA = 6,

  /**
   * @generated from enum value: FSCM_DETAIL_TYPE_FORWARD_EDGE_OF_THE_BATTLE_AREA = 7;
   */
  FSCM_DETAIL_TYPE_FORWARD_EDGE_OF_THE_BATTLE_AREA = 7,

  /**
   * @generated from enum value: FSCM_DETAIL_TYPE_FIRE_SUPPORT_AREA = 8;
   */
  FSCM_DETAIL_TYPE_FIRE_SUPPORT_AREA = 8,

  /**
   * @generated from enum value: FSCM_DETAIL_TYPE_PATROL_RECONNAISSANCE = 9;
   */
  FSCM_DETAIL_TYPE_PATROL_RECONNAISSANCE = 9,

  /**
   * @generated from enum value: FSCM_DETAIL_TYPE_ZONE_OF_RESPONSIBILITY = 10;
   */
  FSCM_DETAIL_TYPE_ZONE_OF_RESPONSIBILITY = 10,

  /**
   * @generated from enum value: FSCM_DETAIL_TYPE_PRIORITY_CALL_FOR_FIRE_ZONE = 11;
   */
  FSCM_DETAIL_TYPE_PRIORITY_CALL_FOR_FIRE_ZONE = 11,

  /**
   * @generated from enum value: FSCM_DETAIL_TYPE_CENSORED_ZONE = 12;
   */
  FSCM_DETAIL_TYPE_CENSORED_ZONE = 12,

  /**
   * @generated from enum value: FSCM_DETAIL_TYPE_ZONE_OF_ACTION = 13;
   */
  FSCM_DETAIL_TYPE_ZONE_OF_ACTION = 13,

  /**
   * @generated from enum value: FSCM_DETAIL_TYPE_CRITICAL_FRIENDLY_ZONE = 14;
   */
  FSCM_DETAIL_TYPE_CRITICAL_FRIENDLY_ZONE = 14,

  /**
   * @generated from enum value: FSCM_DETAIL_TYPE_PLATOON_AREA_HAZARD = 15;
   */
  FSCM_DETAIL_TYPE_PLATOON_AREA_HAZARD = 15,

  /**
   * @generated from enum value: FSCM_DETAIL_TYPE_TARGET_AREA_HAZARD = 16;
   */
  FSCM_DETAIL_TYPE_TARGET_AREA_HAZARD = 16,

  /**
   * @generated from enum value: FSCM_DETAIL_TYPE_RESTRICTED_OPERATIONS_ZONE = 17;
   */
  FSCM_DETAIL_TYPE_RESTRICTED_OPERATIONS_ZONE = 17,

  /**
   * @generated from enum value: FSCM_DETAIL_TYPE_AIR_CORRIDOR = 18;
   */
  FSCM_DETAIL_TYPE_AIR_CORRIDOR = 18,

  /**
   * @generated from enum value: FSCM_DETAIL_TYPE_RESTRICTIVE_FIRE_LINE = 19;
   */
  FSCM_DETAIL_TYPE_RESTRICTIVE_FIRE_LINE = 19,

  /**
   * @generated from enum value: FSCM_DETAIL_TYPE_COORDINATED_FIRE_LINE_NO_FIRE_LINE = 20;
   */
  FSCM_DETAIL_TYPE_COORDINATED_FIRE_LINE_NO_FIRE_LINE = 20,

  /**
   * @generated from enum value: FSCM_DETAIL_TYPE_BOUNDARY_LINE = 21;
   */
  FSCM_DETAIL_TYPE_BOUNDARY_LINE = 21,

  /**
   * @generated from enum value: FSCM_DETAIL_TYPE_FORWARD_LINE = 22;
   */
  FSCM_DETAIL_TYPE_FORWARD_LINE = 22,

  /**
   * @generated from enum value: FSCM_DETAIL_TYPE_FIRE_SUPPORT_LINE = 23;
   */
  FSCM_DETAIL_TYPE_FIRE_SUPPORT_LINE = 23,

  /**
   * @generated from enum value: FSCM_DETAIL_TYPE_LINE_OF_DEPARTURE = 24;
   */
  FSCM_DETAIL_TYPE_LINE_OF_DEPARTURE = 24,

  /**
   * @generated from enum value: FSCM_DETAIL_TYPE_LINE_OF_CONTACT = 25;
   */
  FSCM_DETAIL_TYPE_LINE_OF_CONTACT = 25,

  /**
   * @generated from enum value: FSCM_DETAIL_TYPE_LINE_OF_DEPARTURE_LINE_OF_CONTACT = 26;
   */
  FSCM_DETAIL_TYPE_LINE_OF_DEPARTURE_LINE_OF_CONTACT = 26,

  /**
   * @generated from enum value: FSCM_DETAIL_TYPE_ZONE_OF_FIRE = 27;
   */
  FSCM_DETAIL_TYPE_ZONE_OF_FIRE = 27,
}

/**
 * @generated from enum anduril.entitymanager.v1.ACMDetailType
 */
export declare enum ACMDetailType {
  /**
   * @generated from enum value: ACM_DETAIL_TYPE_INVALID = 0;
   */
  ACM_DETAIL_TYPE_INVALID = 0,

  /**
   * @generated from enum value: ACM_DETAIL_TYPE_AIR_CORRIDOR = 1;
   */
  ACM_DETAIL_TYPE_AIR_CORRIDOR = 1,

  /**
   * @generated from enum value: ACM_DETAIL_TYPE_MINIMUM_RISK_ROUTE = 2;
   */
  ACM_DETAIL_TYPE_MINIMUM_RISK_ROUTE = 2,

  /**
   * @generated from enum value: ACM_DETAIL_TYPE_TEMPORARY_MINIMUM_RISK_ROUTE = 3;
   */
  ACM_DETAIL_TYPE_TEMPORARY_MINIMUM_RISK_ROUTE = 3,

  /**
   * @generated from enum value: ACM_DETAIL_TYPE_TRANSIT_ROUTE = 4;
   */
  ACM_DETAIL_TYPE_TRANSIT_ROUTE = 4,

  /**
   * @generated from enum value: ACM_DETAIL_TYPE_LOW_LEVEL_TRANSIT_ROUTE = 5;
   */
  ACM_DETAIL_TYPE_LOW_LEVEL_TRANSIT_ROUTE = 5,

  /**
   * @generated from enum value: ACM_DETAIL_TYPE_SPECIAL_CORRIDOR = 6;
   */
  ACM_DETAIL_TYPE_SPECIAL_CORRIDOR = 6,

  /**
   * @generated from enum value: ACM_DETAIL_TYPE_STANDARD_USE_ARMY_AIRCRAFT_FLIGHT_ROUTE = 7;
   */
  ACM_DETAIL_TYPE_STANDARD_USE_ARMY_AIRCRAFT_FLIGHT_ROUTE = 7,

  /**
   * @generated from enum value: ACM_DETAIL_TYPE_RESTRICTED_OPERATIONS_ZONE = 8;
   */
  ACM_DETAIL_TYPE_RESTRICTED_OPERATIONS_ZONE = 8,

  /**
   * @generated from enum value: ACM_DETAIL_TYPE_AIR_TO_AIR_REFUELING_AREA = 9;
   */
  ACM_DETAIL_TYPE_AIR_TO_AIR_REFUELING_AREA = 9,

  /**
   * @generated from enum value: ACM_DETAIL_TYPE_AIRBORNE_COMMAND_AND_CONTROL_AREA = 10;
   */
  ACM_DETAIL_TYPE_AIRBORNE_COMMAND_AND_CONTROL_AREA = 10,

  /**
   * @generated from enum value: ACM_DETAIL_TYPE_AIRBORNE_EARLY_WARNING_AREA = 11;
   */
  ACM_DETAIL_TYPE_AIRBORNE_EARLY_WARNING_AREA = 11,

  /**
   * @generated from enum value: ACM_DETAIL_TYPE_CLOSE_AIR_SUPPORT_AREA = 12;
   */
  ACM_DETAIL_TYPE_CLOSE_AIR_SUPPORT_AREA = 12,

  /**
   * @generated from enum value: ACM_DETAIL_TYPE_COMBAT_AIR_PATROL = 13;
   */
  ACM_DETAIL_TYPE_COMBAT_AIR_PATROL = 13,

  /**
   * @generated from enum value: ACM_DETAIL_TYPE_DROP_ZONE = 14;
   */
  ACM_DETAIL_TYPE_DROP_ZONE = 14,

  /**
   * @generated from enum value: ACM_DETAIL_TYPE_ELECTRONIC_COMBAT = 15;
   */
  ACM_DETAIL_TYPE_ELECTRONIC_COMBAT = 15,

  /**
   * @generated from enum value: ACM_DETAIL_TYPE_LANDING_ZONE = 16;
   */
  ACM_DETAIL_TYPE_LANDING_ZONE = 16,

  /**
   * @generated from enum value: ACM_DETAIL_TYPE_PICKUP_ZONE = 17;
   */
  ACM_DETAIL_TYPE_PICKUP_ZONE = 17,

  /**
   * @generated from enum value: ACM_DETAIL_TYPE_RECONNAISSANCE_AREA = 18;
   */
  ACM_DETAIL_TYPE_RECONNAISSANCE_AREA = 18,

  /**
   * @generated from enum value: ACM_DETAIL_TYPE_SPECIAL_OPERATIONS_FORCE_AREA = 19;
   */
  ACM_DETAIL_TYPE_SPECIAL_OPERATIONS_FORCE_AREA = 19,

  /**
   * @generated from enum value: ACM_DETAIL_TYPE_SURFACE_TO_SURFACE_MISSILE_SYSTEM = 20;
   */
  ACM_DETAIL_TYPE_SURFACE_TO_SURFACE_MISSILE_SYSTEM = 20,

  /**
   * @generated from enum value: ACM_DETAIL_TYPE_SURFACE_TO_SURFACE_MUNITIONS = 21;
   */
  ACM_DETAIL_TYPE_SURFACE_TO_SURFACE_MUNITIONS = 21,

  /**
   * @generated from enum value: ACM_DETAIL_TYPE_UNMANNED_AIRCRAFT_AREA = 22;
   */
  ACM_DETAIL_TYPE_UNMANNED_AIRCRAFT_AREA = 22,

  /**
   * @generated from enum value: ACM_DETAIL_TYPE_COORDINATING_ALTITUDE = 23;
   */
  ACM_DETAIL_TYPE_COORDINATING_ALTITUDE = 23,

  /**
   * @generated from enum value: ACM_DETAIL_TYPE_COORDINATION_LEVEL = 24;
   */
  ACM_DETAIL_TYPE_COORDINATION_LEVEL = 24,

  /**
   * @generated from enum value: ACM_DETAIL_TYPE_HIGH_DENSITY_AIRSPACE_CONTROL_ZONE = 25;
   */
  ACM_DETAIL_TYPE_HIGH_DENSITY_AIRSPACE_CONTROL_ZONE = 25,

  /**
   * @generated from enum value: ACM_DETAIL_TYPE_NO_FLY_AREA = 26;
   */
  ACM_DETAIL_TYPE_NO_FLY_AREA = 26,

  /**
   * @generated from enum value: ACM_DETAIL_TYPE_TRANSIT_CORRIDOR = 27;
   */
  ACM_DETAIL_TYPE_TRANSIT_CORRIDOR = 27,

  /**
   * @generated from enum value: ACM_DETAIL_TYPE_RETURN_TO_FORCE = 28;
   */
  ACM_DETAIL_TYPE_RETURN_TO_FORCE = 28,
}

/**
 * @generated from enum anduril.entitymanager.v1.AmmoRestrictionType
 */
export declare enum AmmoRestrictionType {
  /**
   * @generated from enum value: AMMO_RESTRICTION_TYPE_INVALID = 0;
   */
  INVALID = 0,

  /**
   * @generated from enum value: AMMO_RESTRICTION_TYPE_HIGH_EXPLOSIVE_MUNITIONS = 1;
   */
  HIGH_EXPLOSIVE_MUNITIONS = 1,

  /**
   * @generated from enum value: AMMO_RESTRICTION_TYPE_IMPROVED_CONVENTIONAL_MUNITIONS = 2;
   */
  IMPROVED_CONVENTIONAL_MUNITIONS = 2,

  /**
   * @generated from enum value: AMMO_RESTRICTION_TYPE_CHEMICAL_MUNITIONS = 3;
   */
  CHEMICAL_MUNITIONS = 3,

  /**
   * @generated from enum value: AMMO_RESTRICTION_TYPE_NUCLEAR_MUNITIONS = 4;
   */
  NUCLEAR_MUNITIONS = 4,

  /**
   * @generated from enum value: AMMO_RESTRICTION_TYPE_WHITE_PHOSPHORUS_MUNITIONS = 5;
   */
  WHITE_PHOSPHORUS_MUNITIONS = 5,

  /**
   * @generated from enum value: AMMO_RESTRICTION_TYPE_ILLUMINATION_MUNITIONS = 6;
   */
  ILLUMINATION_MUNITIONS = 6,

  /**
   * @generated from enum value: AMMO_RESTRICTION_TYPE_TERMINAL_HOMING_MUNITIONS = 7;
   */
  TERMINAL_HOMING_MUNITIONS = 7,

  /**
   * @generated from enum value: AMMO_RESTRICTION_TYPE_FASCAM_MUNITIONS = 8;
   */
  FASCAM_MUNITIONS = 8,

  /**
   * @generated from enum value: AMMO_RESTRICTION_TYPE_SMOKE_MUNITIONS = 9;
   */
  SMOKE_MUNITIONS = 9,

  /**
   * @generated from enum value: AMMO_RESTRICTION_TYPE_ALL_MUNITIONS = 10;
   */
  ALL_MUNITIONS = 10,
}

/**
 * @generated from enum anduril.entitymanager.v1.RestrictiveMeasureType
 */
export declare enum RestrictiveMeasureType {
  /**
   * @generated from enum value: RESTRICTIVE_MEASURE_TYPE_INVALID = 0;
   */
  INVALID = 0,

  /**
   * @generated from enum value: RESTRICTIVE_MEASURE_TYPE_STAY_INSIDE_AREA = 1;
   */
  STAY_INSIDE_AREA = 1,

  /**
   * @generated from enum value: RESTRICTIVE_MEASURE_TYPE_STAY_OUTSIDE_AREA = 2;
   */
  STAY_OUTSIDE_AREA = 2,

  /**
   * @generated from enum value: RESTRICTIVE_MEASURE_TYPE_STAY_ABOVE_AREA = 3;
   */
  STAY_ABOVE_AREA = 3,

  /**
   * @generated from enum value: RESTRICTIVE_MEASURE_TYPE_STAY_BELOW_AREA = 4;
   */
  STAY_BELOW_AREA = 4,

  /**
   * @generated from enum value: RESTRICTIVE_MEASURE_TYPE_STAY_NORTH_OF_LINE = 5;
   */
  STAY_NORTH_OF_LINE = 5,

  /**
   * @generated from enum value: RESTRICTIVE_MEASURE_TYPE_STAY_EAST_OF_LINE = 6;
   */
  STAY_EAST_OF_LINE = 6,

  /**
   * @generated from enum value: RESTRICTIVE_MEASURE_TYPE_STAY_SOUTH_OF_LINE = 7;
   */
  STAY_SOUTH_OF_LINE = 7,

  /**
   * @generated from enum value: RESTRICTIVE_MEASURE_TYPE_STAY_WEST_OF_LINE = 8;
   */
  STAY_WEST_OF_LINE = 8,
}

/**
 * @generated from enum anduril.entitymanager.v1.MCMDetailType
 */
export declare enum MCMDetailType {
  /**
   * @generated from enum value: MCM_DETAIL_TYPE_INVALID = 0;
   */
  MCM_DETAIL_TYPE_INVALID = 0,

  /**
   * @generated from enum value: MCM_DETAIL_TYPE_NAMED_AREA_OF_INTEREST = 1;
   */
  MCM_DETAIL_TYPE_NAMED_AREA_OF_INTEREST = 1,

  /**
   * @generated from enum value: MCM_DETAIL_TYPE_TARGET_AREA_OF_INTEREST = 2;
   */
  MCM_DETAIL_TYPE_TARGET_AREA_OF_INTEREST = 2,
}

/**
 * A component that describes a geo-entity.
 *
 * @generated from message anduril.entitymanager.v1.GeoDetails
 */
export declare class GeoDetails extends Message<GeoDetails> {
  /**
   * @generated from field: anduril.entitymanager.v1.GeoType type = 1;
   */
  type: GeoType;

  /**
   * any additional type specific details
   *
   * @generated from oneof anduril.entitymanager.v1.GeoDetails.type_details
   */
  typeDetails: {
    /**
     * @generated from field: anduril.entitymanager.v1.EmergencyDetails emergency = 2;
     */
    value: EmergencyDetails;
    case: "emergency";
  } | {
    /**
     * @generated from field: anduril.entitymanager.v1.FSCMDetails fscm = 4;
     */
    value: FSCMDetails;
    case: "fscm";
  } | {
    /**
     * @generated from field: anduril.entitymanager.v1.ControlAreaDetails control_area = 5;
     */
    value: ControlAreaDetails;
    case: "controlArea";
  } | {
    /**
     * @generated from field: anduril.entitymanager.v1.ACMDetails acm = 6;
     */
    value: ACMDetails;
    case: "acm";
  } | {
    /**
     * @generated from field: anduril.entitymanager.v1.MCMDetails mcm = 7;
     */
    value: MCMDetails;
    case: "mcm";
  } | { case: undefined; value?: undefined };

  /**
   * @generated from field: anduril.entitymanager.v1.GeoVisualDetails visual_details = 3;
   */
  visualDetails?: GeoVisualDetails;

  constructor(data?: PartialMessage<GeoDetails>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "anduril.entitymanager.v1.GeoDetails";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GeoDetails;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GeoDetails;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GeoDetails;

  static equals(a: GeoDetails | PlainMessage<GeoDetails> | undefined, b: GeoDetails | PlainMessage<GeoDetails> | undefined): boolean;
}

/**
 * Details specific to a geo-entity of emergency type.
 *
 * @generated from message anduril.entitymanager.v1.EmergencyDetails
 */
export declare class EmergencyDetails extends Message<EmergencyDetails> {
  /**
   * @generated from field: anduril.entitymanager.v1.EmergencyType emergency_type = 1;
   */
  emergencyType: EmergencyType;

  /**
   * @generated from field: uint32 personnel_involved = 2;
   */
  personnelInvolved: number;

  constructor(data?: PartialMessage<EmergencyDetails>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "anduril.entitymanager.v1.EmergencyDetails";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): EmergencyDetails;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): EmergencyDetails;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): EmergencyDetails;

  static equals(a: EmergencyDetails | PlainMessage<EmergencyDetails> | undefined, b: EmergencyDetails | PlainMessage<EmergencyDetails> | undefined): boolean;
}

/**
 * A component that describes the shape of a geo-entity.
 *
 * @generated from message anduril.entitymanager.v1.GeoShape
 */
export declare class GeoShape extends Message<GeoShape> {
  /**
   * point, line_string, and polygon are convertible as a subset of GeoJSON
   *
   * @generated from oneof anduril.entitymanager.v1.GeoShape.shape
   */
  shape: {
    /**
     * @generated from field: anduril.entitymanager.v1.GeoPoint point = 1;
     */
    value: GeoPoint;
    case: "point";
  } | {
    /**
     * @generated from field: anduril.entitymanager.v1.GeoLine line = 2;
     */
    value: GeoLine;
    case: "line";
  } | {
    /**
     * @generated from field: anduril.entitymanager.v1.GeoPolygon polygon = 3;
     */
    value: GeoPolygon;
    case: "polygon";
  } | {
    /**
     * @generated from field: anduril.entitymanager.v1.GeoEllipse ellipse = 4;
     */
    value: GeoEllipse;
    case: "ellipse";
  } | {
    /**
     * @generated from field: anduril.entitymanager.v1.GeoEllipsoid ellipsoid = 5;
     */
    value: GeoEllipsoid;
    case: "ellipsoid";
  } | { case: undefined; value?: undefined };

  constructor(data?: PartialMessage<GeoShape>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "anduril.entitymanager.v1.GeoShape";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GeoShape;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GeoShape;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GeoShape;

  static equals(a: GeoShape | PlainMessage<GeoShape> | undefined, b: GeoShape | PlainMessage<GeoShape> | undefined): boolean;
}

/**
 * A point shaped geo-entity.
 * See https://datatracker.ietf.org/doc/html/rfc7946#section-3.1.2
 *
 * @generated from message anduril.entitymanager.v1.GeoPoint
 */
export declare class GeoPoint extends Message<GeoPoint> {
  /**
   * @generated from field: anduril.entitymanager.v1.Position position = 1;
   */
  position?: Position;

  constructor(data?: PartialMessage<GeoPoint>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "anduril.entitymanager.v1.GeoPoint";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GeoPoint;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GeoPoint;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GeoPoint;

  static equals(a: GeoPoint | PlainMessage<GeoPoint> | undefined, b: GeoPoint | PlainMessage<GeoPoint> | undefined): boolean;
}

/**
 * A line shaped geo-entity.
 * See https://datatracker.ietf.org/doc/html/rfc7946#section-3.1.4
 *
 * @generated from message anduril.entitymanager.v1.GeoLine
 */
export declare class GeoLine extends Message<GeoLine> {
  /**
   * @generated from field: repeated anduril.entitymanager.v1.Position positions = 1;
   */
  positions: Position[];

  constructor(data?: PartialMessage<GeoLine>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "anduril.entitymanager.v1.GeoLine";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GeoLine;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GeoLine;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GeoLine;

  static equals(a: GeoLine | PlainMessage<GeoLine> | undefined, b: GeoLine | PlainMessage<GeoLine> | undefined): boolean;
}

/**
 * A polygon shaped geo-entity.
 * See https://datatracker.ietf.org/doc/html/rfc7946#section-3.1.6, only canonical representations accepted
 *
 * @generated from message anduril.entitymanager.v1.GeoPolygon
 */
export declare class GeoPolygon extends Message<GeoPolygon> {
  /**
   * An array of LinearRings where the first item is the exterior ring and subsequent items are interior rings.
   * For a good introduction read (https://macwright.com/2015/03/23/geojson-second-bite.html#polygons)
   *
   * @generated from field: repeated anduril.entitymanager.v1.LinearRing rings = 1;
   */
  rings: LinearRing[];

  /**
   * An extension hint that this polygon is a rectangle. When true this implies several things:
   * * exactly 1 linear ring with 5 points (starting corner, 3 other corners and start again)
   * * each point has the same altitude corresponding with the plane of the rectangle
   * * each point has the same height (either all present and equal, or all not present)
   *
   * @generated from field: bool is_rectangle = 2;
   */
  isRectangle: boolean;

  constructor(data?: PartialMessage<GeoPolygon>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "anduril.entitymanager.v1.GeoPolygon";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GeoPolygon;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GeoPolygon;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GeoPolygon;

  static equals(a: GeoPolygon | PlainMessage<GeoPolygon> | undefined, b: GeoPolygon | PlainMessage<GeoPolygon> | undefined): boolean;
}

/**
 * An ellipse shaped geo-entity.
 * For a circle, the major and minor axis would be the same values.
 * This shape is NOT Geo-JSON compatible.
 *
 * @generated from message anduril.entitymanager.v1.GeoEllipse
 */
export declare class GeoEllipse extends Message<GeoEllipse> {
  /**
   * Defines the distance from the center point of the ellipse to the furthest distance on the perimeter in meters.
   *
   * @generated from field: google.protobuf.DoubleValue semi_major_axis_m = 2;
   */
  semiMajorAxisM?: number;

  /**
   * Defines the distance from the center point of the ellipse to the shortest distance on the perimeter in meters.
   *
   * @generated from field: google.protobuf.DoubleValue semi_minor_axis_m = 3;
   */
  semiMinorAxisM?: number;

  /**
   * The orientation of the semi-major relative to true north in degrees from clockwise: 0-180 due to symmetry across the semi-minor axis.
   *
   * @generated from field: google.protobuf.DoubleValue orientation_d = 4;
   */
  orientationD?: number;

  /**
   * Optional height above entity position to extrude in meters. A non-zero value creates an elliptic cylinder
   *
   * @generated from field: google.protobuf.DoubleValue height_m = 5;
   */
  heightM?: number;

  constructor(data?: PartialMessage<GeoEllipse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "anduril.entitymanager.v1.GeoEllipse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GeoEllipse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GeoEllipse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GeoEllipse;

  static equals(a: GeoEllipse | PlainMessage<GeoEllipse> | undefined, b: GeoEllipse | PlainMessage<GeoEllipse> | undefined): boolean;
}

/**
 * An ellipsoid shaped geo-entity.
 * Principal axis lengths are defined in entity body space
 * This shape is NOT Geo-JSON compatible.
 *
 * @generated from message anduril.entitymanager.v1.GeoEllipsoid
 */
export declare class GeoEllipsoid extends Message<GeoEllipsoid> {
  /**
   * Defines the distance from the center point to the surface along the forward axis
   *
   * @generated from field: google.protobuf.DoubleValue forward_axis_m = 1;
   */
  forwardAxisM?: number;

  /**
   * Defines the distance from the center point to the surface along the side axis
   *
   * @generated from field: google.protobuf.DoubleValue side_axis_m = 2;
   */
  sideAxisM?: number;

  /**
   * Defines the distance from the center point to the surface along the up axis
   *
   * @generated from field: google.protobuf.DoubleValue up_axis_m = 3;
   */
  upAxisM?: number;

  constructor(data?: PartialMessage<GeoEllipsoid>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "anduril.entitymanager.v1.GeoEllipsoid";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GeoEllipsoid;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GeoEllipsoid;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GeoEllipsoid;

  static equals(a: GeoEllipsoid | PlainMessage<GeoEllipsoid> | undefined, b: GeoEllipsoid | PlainMessage<GeoEllipsoid> | undefined): boolean;
}

/**
 * A closed ring of points. The first and last point must be the same.
 *
 * @generated from message anduril.entitymanager.v1.LinearRing
 */
export declare class LinearRing extends Message<LinearRing> {
  /**
   * Deprecated: do not use, use positions instead
   *
   * @generated from field: repeated anduril.entitymanager.v1.Position points = 1 [deprecated = true];
   * @deprecated
   */
  points: Position[];

  /**
   * @generated from field: repeated anduril.entitymanager.v1.GeoPolygonPosition positions = 2;
   */
  positions: GeoPolygonPosition[];

  constructor(data?: PartialMessage<LinearRing>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "anduril.entitymanager.v1.LinearRing";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): LinearRing;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): LinearRing;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): LinearRing;

  static equals(a: LinearRing | PlainMessage<LinearRing> | undefined, b: LinearRing | PlainMessage<LinearRing> | undefined): boolean;
}

/**
 * A position in a GeoPolygon with an optional extruded height.
 *
 * @generated from message anduril.entitymanager.v1.GeoPolygonPosition
 */
export declare class GeoPolygonPosition extends Message<GeoPolygonPosition> {
  /**
   * base position. if no altitude set, its on the ground.
   *
   * @generated from field: anduril.entitymanager.v1.Position position = 1;
   */
  position?: Position;

  /**
   * optional height above base position to extrude in meters.
   * for a given polygon, all points should have a height or none of them.
   * strictly GeoJSON compatible polygons will not have this set.
   *
   * @generated from field: google.protobuf.FloatValue height_m = 2;
   */
  heightM?: number;

  constructor(data?: PartialMessage<GeoPolygonPosition>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "anduril.entitymanager.v1.GeoPolygonPosition";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GeoPolygonPosition;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GeoPolygonPosition;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GeoPolygonPosition;

  static equals(a: GeoPolygonPosition | PlainMessage<GeoPolygonPosition> | undefined, b: GeoPolygonPosition | PlainMessage<GeoPolygonPosition> | undefined): boolean;
}

/**
 * Details specific to displaying a geo-entity
 *
 * @generated from message anduril.entitymanager.v1.GeoVisualDetails
 */
export declare class GeoVisualDetails extends Message<GeoVisualDetails> {
  /**
   * A string describing the fill color of a geo-entity.
   *
   * @generated from field: anduril.type.Color fill_color = 1;
   */
  fillColor?: Color;

  /**
   * A string describing the line color of a geo-entity.
   *
   * @generated from field: anduril.type.Color line_color = 2;
   */
  lineColor?: Color;

  constructor(data?: PartialMessage<GeoVisualDetails>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "anduril.entitymanager.v1.GeoVisualDetails";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GeoVisualDetails;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GeoVisualDetails;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GeoVisualDetails;

  static equals(a: GeoVisualDetails | PlainMessage<GeoVisualDetails> | undefined, b: GeoVisualDetails | PlainMessage<GeoVisualDetails> | undefined): boolean;
}

/**
 * Details specific to a geo-entity of Fire Support Coordination Measure (FSCM) type
 *
 * @generated from message anduril.entitymanager.v1.FSCMDetails
 */
export declare class FSCMDetails extends Message<FSCMDetails> {
  /**
   * @generated from field: anduril.entitymanager.v1.FSCMDetailType fscm_type = 1;
   */
  fscmType: FSCMDetailType;

  /**
   * Used for loosely typed associations, such as assignment to a specific fires unit
   * Limit to 150 characters
   *
   * @generated from field: string fscm_description = 2;
   */
  fscmDescription: string;

  /**
   * @generated from field: anduril.entitymanager.v1.FiringAuthority firing_authority = 3;
   */
  firingAuthority?: FiringAuthority;

  /**
   * @generated from field: anduril.entitymanager.v1.AmmoRestrictionType ammo_restriction_type = 4 [deprecated = true];
   * @deprecated
   */
  ammoRestrictionType: AmmoRestrictionType;

  /**
   * @generated from field: anduril.entitymanager.v1.RestrictiveMeasureType restrictive_measure_type = 5;
   */
  restrictiveMeasureType: RestrictiveMeasureType;

  /**
   * @generated from field: repeated anduril.entitymanager.v1.AmmoRestrictionType ammo_restrict_types = 6;
   */
  ammoRestrictTypes: AmmoRestrictionType[];

  /**
   * Used to indicate distinction between an FSCM applying to either air or ground, never both
   *
   * @generated from field: bool is_ground = 7;
   */
  isGround: boolean;

  constructor(data?: PartialMessage<FSCMDetails>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "anduril.entitymanager.v1.FSCMDetails";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): FSCMDetails;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): FSCMDetails;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): FSCMDetails;

  static equals(a: FSCMDetails | PlainMessage<FSCMDetails> | undefined, b: FSCMDetails | PlainMessage<FSCMDetails> | undefined): boolean;
}

/**
 * @generated from message anduril.entitymanager.v1.ACMDetails
 */
export declare class ACMDetails extends Message<ACMDetails> {
  /**
   * @generated from field: anduril.entitymanager.v1.ACMDetailType acm_type = 1;
   */
  acmType: ACMDetailType;

  /**
   * Used for loosely typed associations, such as assignment to a specific fires unit
   * Limit to 150 characters
   *
   * @generated from field: string acm_description = 2;
   */
  acmDescription: string;

  constructor(data?: PartialMessage<ACMDetails>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "anduril.entitymanager.v1.ACMDetails";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ACMDetails;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ACMDetails;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ACMDetails;

  static equals(a: ACMDetails | PlainMessage<ACMDetails> | undefined, b: ACMDetails | PlainMessage<ACMDetails> | undefined): boolean;
}

/**
 * @generated from message anduril.entitymanager.v1.MCMDetails
 */
export declare class MCMDetails extends Message<MCMDetails> {
  /**
   * @generated from field: anduril.entitymanager.v1.MCMDetailType mcm_type = 1;
   */
  mcmType: MCMDetailType;

  /**
   * Used for loosely typed associations, such as assignment to a specific fires unit
   * Limit to 150 characters
   *
   * @generated from field: string mcm_description = 2;
   */
  mcmDescription: string;

  constructor(data?: PartialMessage<MCMDetails>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "anduril.entitymanager.v1.MCMDetails";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MCMDetails;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MCMDetails;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MCMDetails;

  static equals(a: MCMDetails | PlainMessage<MCMDetails> | undefined, b: MCMDetails | PlainMessage<MCMDetails> | undefined): boolean;
}

/**
 * Lists the entities that have authority to execute fires into, or through, this FSCM
 *
 * @generated from message anduril.entitymanager.v1.FiringAuthority
 */
export declare class FiringAuthority extends Message<FiringAuthority> {
  /**
   * @generated from field: repeated string entity_ids = 1;
   */
  entityIds: string[];

  constructor(data?: PartialMessage<FiringAuthority>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "anduril.entitymanager.v1.FiringAuthority";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): FiringAuthority;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): FiringAuthority;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): FiringAuthority;

  static equals(a: FiringAuthority | PlainMessage<FiringAuthority> | undefined, b: FiringAuthority | PlainMessage<FiringAuthority> | undefined): boolean;
}

/**
 * Details specific to a geo-entity of the GEO_TYPE_CONTROL_AREA type,
 * representing an autonomous asset Control Area.
 *
 * @generated from message anduril.entitymanager.v1.ControlAreaDetails
 */
export declare class ControlAreaDetails extends Message<ControlAreaDetails> {
  /**
   * @generated from field: anduril.entitymanager.v1.ControlAreaType type = 1;
   */
  type: ControlAreaType;

  constructor(data?: PartialMessage<ControlAreaDetails>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "anduril.entitymanager.v1.ControlAreaDetails";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ControlAreaDetails;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ControlAreaDetails;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ControlAreaDetails;

  static equals(a: ControlAreaDetails | PlainMessage<ControlAreaDetails> | undefined, b: ControlAreaDetails | PlainMessage<ControlAreaDetails> | undefined): boolean;
}

