// @generated by protoc-gen-es v2.0.0
// @generated from file anduril/entitymanager/v1/group.pub.proto (package anduril.entitymanager.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file anduril/entitymanager/v1/group.pub.proto.
 */
export declare const file_anduril_entitymanager_v1_group_pub: GenFile;

/**
 * Details related to grouping for this entity
 *
 * @generated from message anduril.entitymanager.v1.GroupDetails
 */
export declare type GroupDetails = Message<"anduril.entitymanager.v1.GroupDetails"> & {
  /**
   * @generated from oneof anduril.entitymanager.v1.GroupDetails.group_type
   */
  groupType: {
    /**
     * @generated from field: anduril.entitymanager.v1.Team team = 1;
     */
    value: Team;
    case: "team";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message anduril.entitymanager.v1.GroupDetails.
 * Use `create(GroupDetailsSchema)` to create a new message.
 */
export declare const GroupDetailsSchema: GenMessage<GroupDetails>;

/**
 * Describes a Team group type. Comprised of autonomous assets where an asset
 * in a Team can only be a part of a single Team at a time.
 *
 * @generated from message anduril.entitymanager.v1.Team
 */
export declare type Team = Message<"anduril.entitymanager.v1.Team"> & {
};

/**
 * Describes the message anduril.entitymanager.v1.Team.
 * Use `create(TeamSchema)` to create a new message.
 */
export declare const TeamSchema: GenMessage<Team>;

