// @generated by protoc-gen-es v1.7.2 with parameter "js_import_style=legacy_commonjs"
// @generated from file anduril/entitymanager/v1/notification.pub.proto (package anduril.entitymanager.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import type { Entity, Provenance } from "./entity.pub_pb.js";

/**
 * A notification to indicate when a field is overridden on an entity.
 *
 * @generated from message anduril.entitymanager.v1.OverrideNotificationPayload
 */
export declare class OverrideNotificationPayload extends Message<OverrideNotificationPayload> {
  /**
   * The entity containing the values to override and the entityID being overriden.
   * Used by the client to determine the value a field is overridden to (e.g. hostile).
   *
   * @generated from field: anduril.entitymanager.v1.Entity entity = 1;
   */
  entity?: Entity;

  /**
   * The field path determining the path on an entity to override. Used by the client
   * to determine whether an override request was for a particular field (e.g. disposition).
   *
   * @generated from field: string field_path = 2;
   */
  fieldPath: string;

  /**
   * The provenance of the override request. This should always match the OverrideEntityRequest
   * provenance field.
   *
   * @generated from field: anduril.entitymanager.v1.Provenance provenance = 3;
   */
  provenance?: Provenance;

  constructor(data?: PartialMessage<OverrideNotificationPayload>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "anduril.entitymanager.v1.OverrideNotificationPayload";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): OverrideNotificationPayload;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): OverrideNotificationPayload;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): OverrideNotificationPayload;

  static equals(a: OverrideNotificationPayload | PlainMessage<OverrideNotificationPayload> | undefined, b: OverrideNotificationPayload | PlainMessage<OverrideNotificationPayload> | undefined): boolean;
}

