// @generated by protoc-gen-es v1.7.2
// @generated from file anduril/entitymanager/v1/ontology.pub.proto (package anduril.entitymanager.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";
import { Disposition, Environment, Nationality } from "../../ontology/v1/type.pub_pb.js";
import { Template } from "./types.pub_pb.js";

/**
 * Available for Entities that have a military view representation.
 *
 * @generated from message anduril.entitymanager.v1.MilView
 */
export const MilView = proto3.makeMessageType(
  "anduril.entitymanager.v1.MilView",
  () => [
    { no: 1, name: "disposition", kind: "enum", T: proto3.getEnumType(Disposition) },
    { no: 2, name: "environment", kind: "enum", T: proto3.getEnumType(Environment) },
    { no: 3, name: "nationality", kind: "enum", T: proto3.getEnumType(Nationality) },
  ],
);

/**
 * Ontology of the entity.
 *
 * @generated from message anduril.entitymanager.v1.Ontology
 */
export const Ontology = proto3.makeMessageType(
  "anduril.entitymanager.v1.Ontology",
  () => [
    { no: 1, name: "descriptors", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 5, name: "krn", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "platform_type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "specific_type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "template", kind: "enum", T: proto3.getEnumType(Template) },
  ],
);

