// @generated by protoc-gen-es v2.0.0
// @generated from file anduril/entitymanager/v1/relationship.pub.proto (package anduril.entitymanager.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_anduril_entitymanager_v1_sensors_pub } from "./sensors.pub_pb";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file anduril/entitymanager/v1/relationship.pub.proto.
 */
export const file_anduril_entitymanager_v1_relationship_pub = /*@__PURE__*/
  fileDesc("Ci9hbmR1cmlsL2VudGl0eW1hbmFnZXIvdjEvcmVsYXRpb25zaGlwLnB1Yi5wcm90bxIYYW5kdXJpbC5lbnRpdHltYW5hZ2VyLnYxIk4KDVJlbGF0aW9uc2hpcHMSPQoNcmVsYXRpb25zaGlwcxgBIAMoCzImLmFuZHVyaWwuZW50aXR5bWFuYWdlci52MS5SZWxhdGlvbnNoaXAiiQEKDFJlbGF0aW9uc2hpcBIZChFyZWxhdGVkX2VudGl0eV9pZBgBIAEoCRIXCg9yZWxhdGlvbnNoaXBfaWQYAiABKAkSRQoRcmVsYXRpb25zaGlwX3R5cGUYAyABKAsyKi5hbmR1cmlsLmVudGl0eW1hbmFnZXIudjEuUmVsYXRpb25zaGlwVHlwZSL8AgoQUmVsYXRpb25zaGlwVHlwZRIyCgZ0ZXRoZXIYASABKAsyIC5hbmR1cmlsLmVudGl0eW1hbmFnZXIudjEuVGV0aGVySAASOQoKdHJhY2tlZF9ieRgCIAEoCzIjLmFuZHVyaWwuZW50aXR5bWFuYWdlci52MS5UcmFja2VkQnlIABI4Cgljb25maWd1cmUYAyABKAsyIy5hbmR1cmlsLmVudGl0eW1hbmFnZXIudjEuQ29uZmlndXJlSAASOwoLZ3JvdXBfY2hpbGQYBCABKAsyJC5hbmR1cmlsLmVudGl0eW1hbmFnZXIudjEuR3JvdXBDaGlsZEgAEj0KDGdyb3VwX3BhcmVudBgFIAEoCzIlLmFuZHVyaWwuZW50aXR5bWFuYWdlci52MS5Hcm91cFBhcmVudEgAEjsKC21lcmdlZF9mcm9tGAYgASgLMiQuYW5kdXJpbC5lbnRpdHltYW5hZ2VyLnYxLk1lcmdlZEZyb21IAEIGCgR0eXBlIggKBlRldGhlciKRAQoJVHJhY2tlZEJ5EkQKGWFjdGl2ZWx5X3RyYWNraW5nX3NlbnNvcnMYASABKAsyIS5hbmR1cmlsLmVudGl0eW1hbmFnZXIudjEuU2Vuc29ycxI+ChpsYXN0X21lYXN1cmVtZW50X3RpbWVzdGFtcBgCIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXAiCwoJQ29uZmlndXJlIgwKCkdyb3VwQ2hpbGQiDQoLR3JvdXBQYXJlbnQiDAoKTWVyZ2VkRnJvbUKFAgocY29tLmFuZHVyaWwuZW50aXR5bWFuYWdlci52MUIUUmVsYXRpb25zaGlwUHViUHJvdG9QAVpNZ2hlLmFuZHVyaWwuZGV2L2FuZHVyaWwvYW5kdXJpbGFwaXMtZ28vYW5kdXJpbC9lbnRpdHltYW5hZ2VyL3YxO2VudGl0eW1hbmFnZXKiAgNBRViqAhhBbmR1cmlsLkVudGl0eW1hbmFnZXIuVjHKAhhBbmR1cmlsXEVudGl0eW1hbmFnZXJcVjHiAiRBbmR1cmlsXEVudGl0eW1hbmFnZXJcVjFcR1BCTWV0YWRhdGHqAhpBbmR1cmlsOjpFbnRpdHltYW5hZ2VyOjpWMWIGcHJvdG8z", [file_anduril_entitymanager_v1_sensors_pub, file_google_protobuf_timestamp]);

/**
 * Describes the message anduril.entitymanager.v1.Relationships.
 * Use `create(RelationshipsSchema)` to create a new message.
 */
export const RelationshipsSchema = /*@__PURE__*/
  messageDesc(file_anduril_entitymanager_v1_relationship_pub, 0);

/**
 * Describes the message anduril.entitymanager.v1.Relationship.
 * Use `create(RelationshipSchema)` to create a new message.
 */
export const RelationshipSchema = /*@__PURE__*/
  messageDesc(file_anduril_entitymanager_v1_relationship_pub, 1);

/**
 * Describes the message anduril.entitymanager.v1.RelationshipType.
 * Use `create(RelationshipTypeSchema)` to create a new message.
 */
export const RelationshipTypeSchema = /*@__PURE__*/
  messageDesc(file_anduril_entitymanager_v1_relationship_pub, 2);

/**
 * Describes the message anduril.entitymanager.v1.Tether.
 * Use `create(TetherSchema)` to create a new message.
 */
export const TetherSchema = /*@__PURE__*/
  messageDesc(file_anduril_entitymanager_v1_relationship_pub, 3);

/**
 * Describes the message anduril.entitymanager.v1.TrackedBy.
 * Use `create(TrackedBySchema)` to create a new message.
 */
export const TrackedBySchema = /*@__PURE__*/
  messageDesc(file_anduril_entitymanager_v1_relationship_pub, 4);

/**
 * Describes the message anduril.entitymanager.v1.Configure.
 * Use `create(ConfigureSchema)` to create a new message.
 */
export const ConfigureSchema = /*@__PURE__*/
  messageDesc(file_anduril_entitymanager_v1_relationship_pub, 5);

/**
 * Describes the message anduril.entitymanager.v1.GroupChild.
 * Use `create(GroupChildSchema)` to create a new message.
 */
export const GroupChildSchema = /*@__PURE__*/
  messageDesc(file_anduril_entitymanager_v1_relationship_pub, 6);

/**
 * Describes the message anduril.entitymanager.v1.GroupParent.
 * Use `create(GroupParentSchema)` to create a new message.
 */
export const GroupParentSchema = /*@__PURE__*/
  messageDesc(file_anduril_entitymanager_v1_relationship_pub, 7);

/**
 * Describes the message anduril.entitymanager.v1.MergedFrom.
 * Use `create(MergedFromSchema)` to create a new message.
 */
export const MergedFromSchema = /*@__PURE__*/
  messageDesc(file_anduril_entitymanager_v1_relationship_pub, 8);

