// @generated by protoc-gen-es v1.7.2
// @generated from file anduril/entitymanager/v1/transponder_codes.pub.proto (package anduril.entitymanager.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * Indicates the interrogation status of a target.
 *
 * @generated from enum anduril.entitymanager.v1.InterrogationResponse
 */
export const InterrogationResponse = proto3.makeEnum(
  "anduril.entitymanager.v1.InterrogationResponse",
  [
    {no: 0, name: "INTERROGATION_RESPONSE_INVALID", localName: "INVALID"},
    {no: 1, name: "INTERROGATION_RESPONSE_CORRECT", localName: "CORRECT"},
    {no: 2, name: "INTERROGATION_RESPONSE_INCORRECT", localName: "INCORRECT"},
    {no: 3, name: "INTERROGATION_RESPONSE_NO_RESPONSE", localName: "NO_RESPONSE"},
  ],
);

/**
 * A message describing any transponder codes associated with Mode 1, 2, 3, 4, 5, S interrogations.
 *
 * @generated from message anduril.entitymanager.v1.TransponderCodes
 */
export const TransponderCodes = proto3.makeMessageType(
  "anduril.entitymanager.v1.TransponderCodes",
  () => [
    { no: 1, name: "mode1", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 2, name: "mode2", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 3, name: "mode3", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 4, name: "mode4_interrogation_response", kind: "enum", T: proto3.getEnumType(InterrogationResponse) },
    { no: 5, name: "mode5", kind: "message", T: Mode5 },
    { no: 6, name: "mode_s", kind: "message", T: ModeS },
  ],
);

/**
 * Describes the Mode 5 transponder interrogation status and codes.
 *
 * @generated from message anduril.entitymanager.v1.Mode5
 */
export const Mode5 = proto3.makeMessageType(
  "anduril.entitymanager.v1.Mode5",
  () => [
    { no: 1, name: "mode5_interrogation_response", kind: "enum", T: proto3.getEnumType(InterrogationResponse) },
    { no: 2, name: "mode5", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 3, name: "mode5_platform_id", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
  ],
);

/**
 * Describes the Mode S codes.
 *
 * @generated from message anduril.entitymanager.v1.ModeS
 */
export const ModeS = proto3.makeMessageType(
  "anduril.entitymanager.v1.ModeS",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "address", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
  ],
);

