// @generated by protoc-gen-es v2.0.0
// @generated from file anduril/blobs/v1/common.pub.proto (package anduril.blobs.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file anduril/blobs/v1/common.pub.proto.
 */
export const file_anduril_blobs_v1_common_pub = /*@__PURE__*/
  fileDesc("CiFhbmR1cmlsL2Jsb2JzL3YxL2NvbW1vbi5wdWIucHJvdG8SEGFuZHVyaWwuYmxvYnMudjEi4QEKDEJsb2JNZXRhZGF0YRIwCgxjcmVhdGVkX3RpbWUYASABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEjIKDnJldGVudGlvbl90aW1lGAIgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBISCgpzaXplX2J5dGVzGAMgASgEEgsKA21kNRgEIAEoDBIUCgxjb250ZW50X3R5cGUYBSABKAkSNAoKcHJvdmVuYW5jZRgGIAEoCzIgLmFuZHVyaWwuYmxvYnMudjEuQmxvYlByb3ZlbmFuY2UiPQoOQmxvYlByb3ZlbmFuY2USGAoQaW50ZWdyYXRpb25fbmFtZRgBIAEoCRIRCglkYXRhX3R5cGUYAiABKAlCyQEKFGNvbS5hbmR1cmlsLmJsb2JzLnYxQg5Db21tb25QdWJQcm90b1ABWj9naGUuYW5kdXJpbC5kZXYvYW5kdXJpbC9hbmR1cmlsYXBpcy1nby9hbmR1cmlsL2Jsb2JzL3YxO2Jsb2JzdjGiAgNBQliqAhBBbmR1cmlsLkJsb2JzLlYxygIQQW5kdXJpbFxCbG9ic1xWMeICHEFuZHVyaWxcQmxvYnNcVjFcR1BCTWV0YWRhdGHqAhJBbmR1cmlsOjpCbG9iczo6VjFiBnByb3RvMw", [file_google_protobuf_timestamp]);

/**
 * Describes the message anduril.blobs.v1.BlobMetadata.
 * Use `create(BlobMetadataSchema)` to create a new message.
 */
export const BlobMetadataSchema = /*@__PURE__*/
  messageDesc(file_anduril_blobs_v1_common_pub, 0);

/**
 * Describes the message anduril.blobs.v1.BlobProvenance.
 * Use `create(BlobProvenanceSchema)` to create a new message.
 */
export const BlobProvenanceSchema = /*@__PURE__*/
  messageDesc(file_anduril_blobs_v1_common_pub, 1);

