// @generated by protoc-gen-es v2.0.0
// @generated from file anduril/communicationsmanager/v1/blobs.pub.proto (package anduril.communicationsmanager.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_anduril_blobs_v1_filter_pub } from "../../blobs/v1/filter.pub_pb";

/**
 * Describes the file anduril/communicationsmanager/v1/blobs.pub.proto.
 */
export const file_anduril_communicationsmanager_v1_blobs_pub = /*@__PURE__*/
  fileDesc("CjBhbmR1cmlsL2NvbW11bmljYXRpb25zbWFuYWdlci92MS9ibG9icy5wdWIucHJvdG8SIGFuZHVyaWwuY29tbXVuaWNhdGlvbnNtYW5hZ2VyLnYxIi0KF0Jsb2JzSW50ZWdyYXRpb25EZXRhaWxzEhIKCmRhdGFfdHlwZXMYASADKAkiSgoaQmxvYkludGVncmF0aW9uUnVsZURldGFpbHMSLAoHZmlsdGVycxgBIAMoCzIbLmFuZHVyaWwuYmxvYnMudjEuU3RhdGVtZW50QqACCiRjb20uYW5kdXJpbC5jb21tdW5pY2F0aW9uc21hbmFnZXIudjFCDUJsb2JzUHViUHJvdG9QAVpHZ2hlLmFuZHVyaWwuZGV2L2FuZHVyaWwvYW5kdXJpbGFwaXMtZ28vYW5kdXJpbC9jb21tdW5pY2F0aW9uc21hbmFnZXIvdjGiAgNBQ1iqAiBBbmR1cmlsLkNvbW11bmljYXRpb25zbWFuYWdlci5WMcoCIEFuZHVyaWxcQ29tbXVuaWNhdGlvbnNtYW5hZ2VyXFYx4gIsQW5kdXJpbFxDb21tdW5pY2F0aW9uc21hbmFnZXJcVjFcR1BCTWV0YWRhdGHqAiJBbmR1cmlsOjpDb21tdW5pY2F0aW9uc21hbmFnZXI6OlYxYgZwcm90bzM", [file_anduril_blobs_v1_filter_pub]);

/**
 * Describes the message anduril.communicationsmanager.v1.BlobsIntegrationDetails.
 * Use `create(BlobsIntegrationDetailsSchema)` to create a new message.
 */
export const BlobsIntegrationDetailsSchema = /*@__PURE__*/
  messageDesc(file_anduril_communicationsmanager_v1_blobs_pub, 0);

/**
 * Describes the message anduril.communicationsmanager.v1.BlobIntegrationRuleDetails.
 * Use `create(BlobIntegrationRuleDetailsSchema)` to create a new message.
 */
export const BlobIntegrationRuleDetailsSchema = /*@__PURE__*/
  messageDesc(file_anduril_communicationsmanager_v1_blobs_pub, 1);

