// @generated by protoc-gen-es v1.7.2
// @generated from file anduril/communicationsmanager/v1/blobs.pub.proto (package anduril.communicationsmanager.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";
import { Statement } from "../../blobs/v1/filter.pub_pb.js";

/**
 * @generated from message anduril.communicationsmanager.v1.BlobsIntegrationDetails
 */
export const BlobsIntegrationDetails = proto3.makeMessageType(
  "anduril.communicationsmanager.v1.BlobsIntegrationDetails",
  () => [
    { no: 1, name: "data_types", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
  ],
);

/**
 * Message to contain blob integration rules
 *
 * @generated from message anduril.communicationsmanager.v1.BlobIntegrationRuleDetails
 */
export const BlobIntegrationRuleDetails = proto3.makeMessageType(
  "anduril.communicationsmanager.v1.BlobIntegrationRuleDetails",
  () => [
    { no: 1, name: "filters", kind: "message", T: Statement, repeated: true },
  ],
);

