// @generated by protoc-gen-es v1.7.2 with parameter "js_import_style=legacy_commonjs"
// @generated from file anduril/communicationsmanager/v1/communications_manager_api.pub.proto (package anduril.communicationsmanager.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import type { CommunicationsManagerError, DistributionRule, DistributionRuleEvent, Rule, RuleEvent } from "./common.pub_pb.js";

/**
 * @generated from enum anduril.communicationsmanager.v1.RuleType
 */
export declare enum RuleType {
  /**
   * @generated from enum value: RULE_TYPE_INVALID = 0;
   */
  INVALID = 0,

  /**
   * @generated from enum value: RULE_TYPE_ENTITY = 1;
   */
  ENTITY = 1,

  /**
   * @generated from enum value: RULE_TYPE_BLOB = 2;
   */
  BLOB = 2,

  /**
   * @generated from enum value: RULE_TYPE_INTEGRATION = 3;
   */
  INTEGRATION = 3,
}

/**
 * A request to put a rule on this distribution manager.
 *
 * @generated from message anduril.communicationsmanager.v1.PutRuleRequest
 */
export declare class PutRuleRequest extends Message<PutRuleRequest> {
  /**
   * @generated from field: anduril.communicationsmanager.v1.Rule rule = 2;
   */
  rule?: Rule;

  /**
   * To be DEPRECATED. Use `Rule`
   *
   * @generated from field: anduril.communicationsmanager.v1.DistributionRule distribution_rule = 1;
   */
  distributionRule?: DistributionRule;

  constructor(data?: PartialMessage<PutRuleRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "anduril.communicationsmanager.v1.PutRuleRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PutRuleRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PutRuleRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PutRuleRequest;

  static equals(a: PutRuleRequest | PlainMessage<PutRuleRequest> | undefined, b: PutRuleRequest | PlainMessage<PutRuleRequest> | undefined): boolean;
}

/**
 * A response indicating success or failure of the PutRuleRequest.
 *
 * @generated from message anduril.communicationsmanager.v1.PutRuleResponse
 */
export declare class PutRuleResponse extends Message<PutRuleResponse> {
  /**
   * The current version of the rule after attempting to Put a rule. On success, version_num is incremented by 1.
   * On conflict the current, nonupdated version is returned and containing the current version_num.
   *
   * @generated from field: anduril.communicationsmanager.v1.Rule rule = 3;
   */
  rule?: Rule;

  /**
   * Error message returned in the event of an error such as a Proto-KV conflict.
   *
   * @generated from field: anduril.communicationsmanager.v1.CommunicationsManagerError error = 2;
   */
  error?: CommunicationsManagerError;

  /**
   * To be DEPRECATED. Use `Rule`
   *
   * @generated from field: anduril.communicationsmanager.v1.DistributionRule distribution_rule = 1;
   */
  distributionRule?: DistributionRule;

  constructor(data?: PartialMessage<PutRuleResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "anduril.communicationsmanager.v1.PutRuleResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PutRuleResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PutRuleResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PutRuleResponse;

  static equals(a: PutRuleResponse | PlainMessage<PutRuleResponse> | undefined, b: PutRuleResponse | PlainMessage<PutRuleResponse> | undefined): boolean;
}

/**
 * A request to stream rules from this node's distribution manager.
 *
 * @generated from message anduril.communicationsmanager.v1.StreamRulesRequest
 */
export declare class StreamRulesRequest extends Message<StreamRulesRequest> {
  /**
   * @generated from field: repeated anduril.communicationsmanager.v1.RuleType rule_type = 1;
   */
  ruleType: RuleType[];

  /**
   * Stream preexisting rules only and close the stream once all preexisting rules have been provided.
   *
   * @generated from field: bool preexisting_only = 2;
   */
  preexistingOnly: boolean;

  constructor(data?: PartialMessage<StreamRulesRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "anduril.communicationsmanager.v1.StreamRulesRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): StreamRulesRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): StreamRulesRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): StreamRulesRequest;

  static equals(a: StreamRulesRequest | PlainMessage<StreamRulesRequest> | undefined, b: StreamRulesRequest | PlainMessage<StreamRulesRequest> | undefined): boolean;
}

/**
 * A response stream will be fed all matching pre-existing rules first, then
 * receive any ongoing events.
 *
 * @generated from message anduril.communicationsmanager.v1.StreamRulesResponse
 */
export declare class StreamRulesResponse extends Message<StreamRulesResponse> {
  /**
   * @generated from field: anduril.communicationsmanager.v1.RuleEvent rule_event = 2;
   */
  ruleEvent?: RuleEvent;

  /**
   * To be DEPRECATED. Use `RuleEvent`
   *
   * @generated from field: anduril.communicationsmanager.v1.DistributionRuleEvent distribution_rule_event = 1;
   */
  distributionRuleEvent?: DistributionRuleEvent;

  constructor(data?: PartialMessage<StreamRulesResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "anduril.communicationsmanager.v1.StreamRulesResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): StreamRulesResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): StreamRulesResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): StreamRulesResponse;

  static equals(a: StreamRulesResponse | PlainMessage<StreamRulesResponse> | undefined, b: StreamRulesResponse | PlainMessage<StreamRulesResponse> | undefined): boolean;
}

/**
 * A request to delete a rule on this distribution manager.
 *
 * @generated from message anduril.communicationsmanager.v1.DeleteRuleRequest
 */
export declare class DeleteRuleRequest extends Message<DeleteRuleRequest> {
  /**
   * @generated from field: anduril.communicationsmanager.v1.Rule rule = 2;
   */
  rule?: Rule;

  /**
   * To be DEPRECATED. Use `Rule`
   *
   * @generated from field: anduril.communicationsmanager.v1.DistributionRule distribution_rule = 1;
   */
  distributionRule?: DistributionRule;

  constructor(data?: PartialMessage<DeleteRuleRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "anduril.communicationsmanager.v1.DeleteRuleRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeleteRuleRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeleteRuleRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeleteRuleRequest;

  static equals(a: DeleteRuleRequest | PlainMessage<DeleteRuleRequest> | undefined, b: DeleteRuleRequest | PlainMessage<DeleteRuleRequest> | undefined): boolean;
}

/**
 * A response indicating success or failure of the DeleteRuleRequest.
 *
 * @generated from message anduril.communicationsmanager.v1.DeleteRuleResponse
 */
export declare class DeleteRuleResponse extends Message<DeleteRuleResponse> {
  /**
   * The current version of the rule after attempting to delete a rule. On success, distribution_rule is null.
   * On failure, the rule returned is the conflicted version.
   *
   * @generated from field: anduril.communicationsmanager.v1.Rule rule = 3;
   */
  rule?: Rule;

  /**
   * Error message returned in the event of an error such as a Proto-KV conflict.
   *
   * @generated from field: anduril.communicationsmanager.v1.CommunicationsManagerError error = 2;
   */
  error?: CommunicationsManagerError;

  /**
   * To be DEPRECATED. Use `Rule`
   *
   * @generated from field: anduril.communicationsmanager.v1.DistributionRule distribution_rule = 1;
   */
  distributionRule?: DistributionRule;

  constructor(data?: PartialMessage<DeleteRuleResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "anduril.communicationsmanager.v1.DeleteRuleResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeleteRuleResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeleteRuleResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeleteRuleResponse;

  static equals(a: DeleteRuleResponse | PlainMessage<DeleteRuleResponse> | undefined, b: DeleteRuleResponse | PlainMessage<DeleteRuleResponse> | undefined): boolean;
}

