// @generated by protoc-gen-es v2.0.0
// @generated from file anduril/communicationsmanager/v1/cross_domain.pub.proto (package anduril.communicationsmanager.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";

/**
 * Describes the file anduril/communicationsmanager/v1/cross_domain.pub.proto.
 */
export const file_anduril_communicationsmanager_v1_cross_domain_pub = /*@__PURE__*/
  fileDesc("CjdhbmR1cmlsL2NvbW11bmljYXRpb25zbWFuYWdlci92MS9jcm9zc19kb21haW4ucHViLnByb3RvEiBhbmR1cmlsLmNvbW11bmljYXRpb25zbWFuYWdlci52MSIyCg1SZWdpc3RlcmVkQ2RzEg8KB2hvc3RfaWQYASABKAkSEAoIY2RzX25hbWUYAiABKAkiWQoOQ2RzRGVzdGluYXRpb24SRwoOcmVnaXN0ZXJlZF9jZHMYASABKAsyLy5hbmR1cmlsLmNvbW11bmljYXRpb25zbWFuYWdlci52MS5SZWdpc3RlcmVkQ2RzQqYCCiRjb20uYW5kdXJpbC5jb21tdW5pY2F0aW9uc21hbmFnZXIudjFCE0Nyb3NzRG9tYWluUHViUHJvdG9QAVpHZ2hlLmFuZHVyaWwuZGV2L2FuZHVyaWwvYW5kdXJpbGFwaXMtZ28vYW5kdXJpbC9jb21tdW5pY2F0aW9uc21hbmFnZXIvdjGiAgNBQ1iqAiBBbmR1cmlsLkNvbW11bmljYXRpb25zbWFuYWdlci5WMcoCIEFuZHVyaWxcQ29tbXVuaWNhdGlvbnNtYW5hZ2VyXFYx4gIsQW5kdXJpbFxDb21tdW5pY2F0aW9uc21hbmFnZXJcVjFcR1BCTWV0YWRhdGHqAiJBbmR1cmlsOjpDb21tdW5pY2F0aW9uc21hbmFnZXI6OlYxYgZwcm90bzM");

/**
 * Describes the message anduril.communicationsmanager.v1.RegisteredCds.
 * Use `create(RegisteredCdsSchema)` to create a new message.
 */
export const RegisteredCdsSchema = /*@__PURE__*/
  messageDesc(file_anduril_communicationsmanager_v1_cross_domain_pub, 0);

/**
 * Describes the message anduril.communicationsmanager.v1.CdsDestination.
 * Use `create(CdsDestinationSchema)` to create a new message.
 */
export const CdsDestinationSchema = /*@__PURE__*/
  messageDesc(file_anduril_communicationsmanager_v1_cross_domain_pub, 1);

