// @generated by protoc-gen-es v1.7.2 with parameter "js_import_style=legacy_commonjs"
// @generated from file anduril/communicationsmanager/v1/entity.pub.proto (package anduril.communicationsmanager.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

"use strict";
Object.defineProperty(exports, "__esModule", { value: true });

const { proto3 } = require("@bufbuild/protobuf");
const { Statement } = require("../../entitymanager/v1/filter.pub_pb.js");

/**
 * @generated from message anduril.communicationsmanager.v1.EntityIntegrationDetails
 */
const EntityIntegrationDetails = proto3.makeMessageType(
  "anduril.communicationsmanager.v1.EntityIntegrationDetails",
  () => [
    { no: 1, name: "vendors", kind: "message", T: EntityDataVendor, repeated: true },
  ],
);

/**
 * @generated from message anduril.communicationsmanager.v1.EntityDataVendor
 */
const EntityDataVendor = proto3.makeMessageType(
  "anduril.communicationsmanager.v1.EntityDataVendor",
  () => [
    { no: 1, name: "vendor_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "data_type", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
  ],
);

/**
 * Message to contain entity integration rules
 *
 * @generated from message anduril.communicationsmanager.v1.EntityIntegrationRuleDetails
 */
const EntityIntegrationRuleDetails = proto3.makeMessageType(
  "anduril.communicationsmanager.v1.EntityIntegrationRuleDetails",
  () => [
    { no: 1, name: "filter", kind: "message", T: Statement },
  ],
);


exports.EntityIntegrationDetails = EntityIntegrationDetails;
exports.EntityDataVendor = EntityDataVendor;
exports.EntityIntegrationRuleDetails = EntityIntegrationRuleDetails;
