/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as lattice from "../index.js";

/**
 * A component to represent a frequency range.
 */
export interface FrequencyRange {
    /** Indicates the lowest measured frequency of a signal (Hz). */
    minimumFrequencyHz?: lattice.Frequency;
    /** Indicates the maximum measured frequency of a signal (Hz). */
    maximumFrequencyHz?: lattice.Frequency;
}
