/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as lattice from "../index.js";

/**
 * A line shaped geo-entity.
 *  See https://datatracker.ietf.org/doc/html/rfc7946#section-3.1.4
 */
export interface GeoLine {
    positions?: lattice.Position[];
}
