/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as lattice from "../index.js";

/**
 * Details related to grouping for this entity
 */
export interface GroupDetails {
    team?: lattice.Team;
    echelon?: lattice.Echelon;
}
