/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as lattice from "../index.js";

/**
 * Metadata about entity overrides present.
 */
export interface Overrides {
    override?: lattice.Override[];
}
