/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as lattice from "../index.js";

export interface PathMetadata {
    content_identifier: lattice.ContentIdentifier;
    size_bytes: number;
    last_updated_at: string;
    expiry_time?: string;
}
