/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as lattice from "../index.js";

/**
 * Determines the type of relationship between this entity and another.
 */
export interface RelationshipType {
    trackedBy?: lattice.TrackedBy;
    groupChild?: lattice.GroupChild;
    groupParent?: lattice.GroupParent;
    mergedFrom?: lattice.MergedFrom;
    activeTarget?: lattice.ActiveTarget;
}
