/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as lattice from "../index.js";

/**
 * A component that describes an entity's signal characteristics.
 */
export interface Signal {
    frequencyCenter?: lattice.Frequency;
    frequencyRange?: lattice.FrequencyRange;
    /** Indicates the bandwidth of a signal (Hz). */
    bandwidthHz?: number;
    /** Indicates the signal to noise (SNR) of this signal. */
    signalToNoiseRatio?: number;
    lineOfBearing?: lattice.LineOfBearing;
    fixed?: lattice.Fixed;
    /** Emitter notations associated with this entity. */
    emitterNotations?: lattice.EmitterNotation[];
    /** length in time of a single pulse */
    pulseWidthS?: number;
    /** length in time between the start of two pulses */
    pulseRepetitionInterval?: lattice.PulseRepetitionInterval;
    /** describes how a signal is observing the environment */
    scanCharacteristics?: lattice.ScanCharacteristics;
}
